version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/chatdb
    volumes:
      - .:/app
    networks:
      - chat-network

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chatdb
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - chat-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_PORT=5432
      - PMA_USER=postgres
      - PMA_PASSWORD=postgres
      - PMA_ARBITRARY=1
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - chat-network

volumes:
  db-data:
    driver: local

networks:
  chat-network:
    driver: bridge